import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import GeneralLayout from "@/layout/general-layout";
import Hero from "@/components/home/hero";
import Container from "@/components/container";
import Slogan from "@/components/home/slogan";
import Offers from "@/components/home/challenges";
import FullBodyWorkout from "@/components/home/full-body-workout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GeneralLayout>
        <Container modifierClasses="mt-40 md:mt-24">
          <Hero />
          <Slogan />
          <Offers />
          <FullBodyWorkout />
        </Container>
      </GeneralLayout>
    </div>
  );
}
